version: '3'
services:
  mariadb:
    image: mariadb:11
    container_name: crm-mariadb
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend-net
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: crm-adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  backend-net:
    external: true
